### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Minh-Nguyen22** [Minh-Nguyen22/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by MyFriend22** [comment]
інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро інтро
