### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Minh-Nguyen22** [Minh-Nguyen22/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by MyFriend22** [comment]
блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації блок контактної інформації
