### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Minh-Nguyen22** [Minh-Nguyen22/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by MyFriend22** [comment]
додаткові інформаційні блоки додаткові інформаційні блоки додаткові інформаційні блоки додаткові інформаційні блоки додаткові інформаційні блоки додаткові інформаційні блоки додаткові інформаційні блоки додаткові інформаційні блоки додаткові інформаційні блоки додаткові інформаційні блоки додаткові інформаційні блоки додаткові інформаційні блоки

**Comment by Minh-Nguyen22** [comment]
OKKKKKKKK
